version: "3.4"

services:
    api:
        container_name: store-crm-api
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db
        volumes: 
          - ./attachments:/StoreCRM/attachments

    db:
        container_name: store-crm-db
        hostname: postgres
        image: "postgres:latest"
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data

    pgadmin:
        container_name: pg-admin
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"